<?php
namespace app\modules\v1\controllers;

use common\models\Transaction;
use common\models\user\nestedSets\UserLink;
use common\models\user\User;
use yii;
use yii\filters\auth\HttpBearerAuth;
use common\models\TransactionTotal;

class RankController extends BaseActiveController
{

    public $modelClass = 'common\models\user\User';

    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::className()
        ];
        return $behaviors;
    }

    /**
     * 激活排行
     */
    public function actionActivateList()
    {
        $limit = 10;

        // 获取我的交易统计信息
        $userTransaction = TransactionTotal::findOne(['user_id'=>Yii::$app->user->identity->id]);
        if($userTransaction === null){
            $userTransaction = new TransactionTotal();
            $userTransaction->load([
                "agent_id" => Yii::$app->user->identity->agent_id,
                "user_id" => Yii::$app->user->identity->id,
                "num" => 0,
                "total_money" => 0,
            ], '');
            $userTransaction->save();
        }

        $myTransaction = $userTransaction->toArray();

        $field = 'num';
        $total = TransactionTotal::getMyTotalField(Yii::$app->user->id, $field);
        $myTransaction['num'] = $total ? $total : 0;

        // 我的排名
        $myTransaction['user']['id'] = Yii::$app->user->id;
        $myTransaction['user']['avatar'] = Yii::$app->user->identity->avatar;
        $myTransaction['mobile'] = substr_replace(Yii::$app->user->identity->mobile, '****', 3,4);
        if(!empty($myTransaction['num'])){

            $myRank = TransactionTotal::getMyTotalFieldRank($myTransaction['user_id'], $myTransaction['agent_id'], $field, $total);
            $myTransaction['rank'] = $myRank ? $myRank : '-';

        } else {
            $myTransaction['rank'] = '-';
        }

        // 查询前10名
        $rankTop = TransactionTotal::getRankList($myTransaction['agent_id'], $field);

        unset($myTransaction['total_money']);
        $data = [];
        $data['me'] = $myTransaction;
        foreach($rankTop as $key=> $val)
        {
            $row = [
                "id" => 0,
                "agent_id" => $val['agent_id'],
                "user_id" => $val['user_id'],
                "num" => $val['num'],
//                "total_money" => $val['total_money'],
                "created_at" => $val['created_at'],
                "user" => [
                    "id" => $val['user_id'],
                    "avatar" => $val['avatar']
                ],
                "mobile" => substr_replace($val['mobile'], '****', 3,4),
                "rank" => $key +1
            ];

            $data['all'][$key] = $row;
        }

        if(empty($data))
        {
            return [
                'status' => 0,
                'code' => 0,
                'message' => '没有数据',
                'data' => []
            ];
        }
        return [
            'status' => 0,
            'code' => 200,
            'message' => [],
            'data' => $data
        ];

    }

    /**
     * @return array交易排行
     */
    public function actionTotalAmountList()
    {
        $limit = 10;

        // 获取我的交易统计信息
        $userTransaction = TransactionTotal::findOne(['user_id'=>Yii::$app->user->identity->id]);
        if($userTransaction === null){
            $userTransaction = new TransactionTotal();
            $userTransaction->load([
                "agent_id" => Yii::$app->user->identity->agent_id,
                "user_id" => Yii::$app->user->identity->id,
                "num" => 0,
                "total_money" => 0,
            ], '');
            $userTransaction->save();
        }

        $myTransaction = $userTransaction->toArray();

        $field = 'total_money';
        $total = TransactionTotal::getMyTotalField(Yii::$app->user->id, $field);
        $myTransaction['total_money'] = $total ? $total : 0;

        // 我的排名
        $myTransaction['user']['id'] = Yii::$app->user->identity->id;
        $myTransaction['user']['avatar'] = Yii::$app->user->identity->avatar;
        $myTransaction['mobile'] = substr_replace(Yii::$app->user->identity->mobile, '****', 3,4);
        if(!empty($myTransaction['total_money'])){

            $myRank = TransactionTotal::getMyTotalFieldRank($myTransaction['user_id'], $myTransaction['agent_id'], $field, $total);
            $myTransaction['rank'] = $myRank ? $myRank : 0;

        } else {
            $myTransaction['rank'] = '-';
        }

        // 查询交易前10名
        $rankTop = TransactionTotal::getRankList($myTransaction['agent_id'], $field);

        unset($myTransaction['num']);
        $data = [];
        $data['me'] = $myTransaction;
        foreach($rankTop as $key=> $val)
        {
            $row = [
                "id" => 0,
                "agent_id" => $val['agent_id'],
                "user_id" => $val['user_id'],
//                "num" => $val['num'],
                "total_money" => $val['total_money'],
                "created_at" => $val['created_at'],
                "user" => [
                    "id" => $val['user_id'],
                    "avatar" => $val['avatar']
                ],
                "mobile" => substr_replace($val['mobile'], '****', 3,4),
                "rank" => $key +1
            ];

            $data['all'][$key] = $row;
        }
        if(empty($data))
        {
            return [
                'status' => 0,
                'code' => 0,
                'message' => '没有数据',
                'data' => []
            ];
        }
        return [
            'status' => 0,
            'code' => 200,
            'message' => [],
            'data' => $data
        ];

    }
}