<?php
namespace app\modules\v1\controllers;

use yii;
use yii\web\Controller;
use yii\helpers\Url;
use yii\filters\auth\HttpBearerAuth;
use common\models\app\AppShare;
use common\services\app\ShareRegisterForm;

class ShareController extends BaseActiveController
{

    public $modelClass = 'common\models\user\User';

    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::className(),
            'optional' => [
            ]
        ];
        
        return $behaviors;
    }

    public function actionImageList()
    {
        $model = AppShare::find();
        $model->andWhere([
            'status' => AppShare::START
        ]);
        $model->orderBy(['sort'=>SORT_DESC]);
        $data = $model->asArray()->all();
        foreach ($data as $key => $val) {
            $img_arr[$key]['image'] = $val['image'];
            $img_arr[$key]['id'] = $val['id'];
            $img_arr[$key]['qrcodeUrl'] = Url::toRoute([
                '/site/register',
                'user_id' => Yii::$app->user->id,
                'mobile' => Yii::$app->user->identity->mobile
            ], true);
        }
        return [
            'status' => 0,
            'code' => 200,
            'message' => [
                ''
            ],
            'data' => $img_arr
        ];
    }
}